import React from "react";
import { View, StyleSheet, FlatList } from "react-native";
import BookSection from "../components/BookSection";

const handoutData = [
      { id: 1, title : "ACC501 - Business Finance",  pdfUrl:"https://vukhanpur.com/handouts/ACC501_handouts_1_45.pdf" },
      { id: 2, title: "BIF401 - Bioinformatics I",  pdfUrl: "https://vukhanpur.com/handouts/BIF401_handouts.pdf" },
      { id: 3, title : "BIF501 - Bioinformatics-II",  pdfUrl:"https://vukhanpur.com/handouts/BIF501.pdf"},
      { id: 4, title : "BIF601 - Bioinformatics Computing I",  pdfUrl:"https://vukhanpur.com/handouts/BIF601-Introduction_to_Computational_Biology.pdf"},
      { id: 5, title : "BIF602 - Bioinformatics Computing II",  pdfUrl:"https://vukhanpur.com/handouts/BIF602_handouts.pdf"},
      { id: 6, title : "BIF604 - Special Topics in Bioinformatics",  pdfUrl:"https://vukhanpur.com/handouts/BIF604_handouts.pdf"},
      { id: 7, title : "BIO202 - Biochemistry-I",  pdfUrl:"https://vukhanpur.com/handouts/BIO202-Handouts-1_45.pdf"},
      { id: 8, title : "BIO203 - Methods in Molecular Biology",  pdfUrl:"https://vukhanpur.com/handouts/BIO203_complete_PPTz._Printable-1.pdf"},
      { id: 9, title : "BIO301 - Essentials of Genetics",  pdfUrl:"https://vukhanpur.com/handouts/BIO301_handouts_1_167.pdf"},
      { id: 10, title : "BIO302 - Molecular Biology",  pdfUrl:"https://vukhanpur.com/handouts/Bio302-Handouts.pdf"},
      { id: 11, title : "BIO303 - Biochemistry-II",  pdfUrl:"https://vukhanpur.com/handouts/BIO_303.pdf"},
      { id: 12, title : "BIO401 - Biostatistics",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_of__Biostatics.pdf"},
      { id: 13, title : "BIO502 - Genomics",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_Genomics.docx"},
      { id: 14, title : "BIO503 - Biological Physics",  pdfUrl:"https://vukhanpur.com/handouts/BIO503_handouts_biological_physics.pdf"},
      { id: 15, title : "BIO601 - Proteomics",  pdfUrl:"https://vukhanpur.com/handouts/book__genomics_proteomics.pdf"},
      { id: 16, title : "BNK601 - Banking Laws & Practices",  pdfUrl:"https://vukhanpur.com/handouts/BNK601_handouts_1_45.pdf"},
      { id: 17, title : "BT101 - Ecology, Biodiversity & Evolution-I",  pdfUrl:"https://vukhanpur.com/handouts/BT101_Ecology,_Biodiversity_And_Evolution-I_Complete_Ppts_[Downloaded_From_Cluesbook.com].pdf"},
      { id: 18, title : "BT102 - Microbiology",  pdfUrl:"https://vukhanpur.com/handouts/Microbiology_Handouts_BT-102.pdf"},
      { id: 19, title : "BT201 - Ecology, Biodiversity & Evolution-II",  pdfUrl:"https://vukhanpur.com/handouts/BT201_Ecology,_Biodiversity_&_Evolution-II_(_1_to_70_)full_mid_and_final_merged_ppt_handouts.pdf"},
      { id: 20, title : "BT301 - Introduction to Biotechnology",  pdfUrl:"https://vukhanpur.com/handouts/BT301_1-209_Complete_Handouts.pdf"},
      { id: 21, title : "BT302 - Immunology",  pdfUrl:"https://vukhanpur.com/handouts/BT302_PPT_Slide_1_To_167_1pOn4_view_By_vuways.com(Zarva_Chaudhary).pdf"},
      { id: 22, title : "BT401 - Resources & Conservation",  pdfUrl:"https://vukhanpur.com/handouts/handouts_(1).pdf"},
      { id: 23, title : "BT403 - Agriculture Biotechnology",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_of_Agriculture_Biotechnology.pdf"},
      { id: 24, title : "BT405 - Nano Biotechnology",  pdfUrl:"https://vukhanpur.com/handouts/BT405_handouts.pdf"},
      { id: 25, title : "BT406 - Research Methodology & Skill Enhancement",  pdfUrl:"https://vukhanpur.com/handouts/BT406_-Research_Methodology___Skill_Enhancement(_merged_ppt__full_1_to_43_)_mid_and_final.pdf"},
      { id: 26, title : "BT501 - Health Biotechnology",  pdfUrl:"https://vukhanpur.com/handouts/BT501.pdf"},
      { id: 27, title : "BT503 - Environmental Biotechnology",  pdfUrl:"https://vukhanpur.com/handouts/BT_503.pdf"},
      { id: 28, title : "BT504 - Genomics and Proteomics",  pdfUrl:"https://vukhanpur.com/handouts/BT504_Genomics_And_Proteomics_Complete_Handouts.pdf"},
      { id: 29, title : "BT505 - Biosensor",  pdfUrl:"https://vukhanpur.com/handouts/BT505_BIOSENSORS_Handouts.pdf"},
      { id: 30, title : "BT601 - Virology",  pdfUrl:"https://vukhanpur.com/handouts/BT601_Virology_Complete_Handouts_[Downloaded_From_Cluesbook.com].pdf"},
      { id: 31, title : "BT605 - Biosafety & Bioethics",  pdfUrl:"https://vukhanpur.com/handouts/BT_605.pdf"},
      { id: 32, title : "CHE201 - Physical Chemistry",  pdfUrl:"https://vukhanpur.com/handouts/handouts_3.pdf"},
      { id: 33, title : "CHE301 - Analytical Chemistry and Instrumentation",  pdfUrl:"https://vukhanpur.com/handouts/che301_Handouts_(1).pdf"},
      { id: 34, title : "CS001 - Computer Proficiency License",  pdfUrl:"https://vukhanpur.com/handouts/CS001_Handouts075812.pdf"},
      { id: 35, title : "Cs101 - Introduction to Computing",  pdfUrl:"https://vukhanpur.com/handouts/CS101_Updated_Handouts-1.pdf"},
      { id: 36, title : "CS201 - Introduction to Programming",  pdfUrl:"https://vukhanpur.com/handouts/cs201_Handouts.pdf"},
      { id: 37, title : "CS202 - Fundamentals of Front End Development",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_[CS202_-_Fundamentals_of_Front_End_Development].pdf"},
      { id: 38, title : "CS204 - Cyber Security",  pdfUrl:"https://vukhanpur.com/handouts/CS204_HANDOUT.pdf"},
      { id: 39, title : "CS205 - Information Security",  pdfUrl:"https://vukhanpur.com/handouts/CS205_-_Information_Security_Handouts.pdf"},
      { id: 40, title : "CS205 - Information Security",  pdfUrl:"https://vukhanpur.com/handouts/CS205_-_Information_Security_Handouts051036.pdf"},
      { id: 41, title : "CS301 - Data Structures",  pdfUrl:"https://vukhanpur.com/handouts/CS301_handouts_(Updated).pdf"},
      { id: 42, title : "CS302 - Digital Logic Design",  pdfUrl:"https://vukhanpur.com/handouts/CS302_-_Digital_Logic_and_Design_Handouts_(1-45_lectures).pdf"},
      { id: 43, title : "CS304 - Object Oriented Programming",  pdfUrl:"https://vukhanpur.com/handouts/CS304_Handouts_(Updated).pdf"},
      { id: 44, title : "CS310 - Open Source Web Application Development (PHP, PERL, CGI, Mysql)",  pdfUrl:"https://vukhanpur.com/handouts/CS310OpenSourceWebApplicationDevelopmentPHPPERLCGIMysqlCompleteHandoutsByWahabAhmadFatimaAli.pdf"},
      { id: 45, title : "CS401 - Computer Architecture and Assembly Language Programming",  pdfUrl:"https://vukhanpur.com/handouts/cs401.pdf"},
      { id: 46, title : "CS402 - Theory of Automata",  pdfUrl:"https://vukhanpur.com/handouts/CS402_handouts_1_45.pdf"},
      { id: 47, title : "CS402 - Theory of Automata",  pdfUrl:"https://vukhanpur.com/handouts/CS402_handouts_1_451.pdf"},
      { id: 48, title : "CS403 - Database Management System",  pdfUrl:"https://vukhanpur.com/handouts/CS403-Database-Management-Systems-Complete-Handouts-Pdf.pdf"},
      { id: 49, title : "CS407 - Routing and Switching",  pdfUrl:"https://vukhanpur.com/handouts/Handout_CS407_-_Routing_and_Switching.pdf"},
      { id: 50, title : "CS408 - Human Computer Interaction",  pdfUrl:"https://vukhanpur.com/handouts/CS408_HCI_Handouts_1-45.pdf"},
      { id: 51, title : "CS411 - Visual Programming",  pdfUrl:"https://vukhanpur.com/handouts/CS411_handouts_1_45.pdf"},
      { id: 52, title : "CS435 - Cloud Computing",  pdfUrl:"https://vukhanpur.com/handouts/CS435_Handouts_-Cloud_Computing_V4_(1).docx"},
      { id: 53, title : "CS501 - Advance Computer Architecture",  pdfUrl:"https://vukhanpur.com/handouts/CS501_handouts_1_45.pdf"},
      { id: 54, title : "CS502 - Fundamentals of Algorithms",  pdfUrl:"https://vukhanpur.com/handouts/CS502-highlights.pdf"},
      { id: 55, title : "CS504 - Engineering-I",  pdfUrl:"https://vukhanpur.com/handouts/CS504_handouts_1_45.pdf"},
      { id: 56, title : "CS506 - Web Design and development",  pdfUrl:"https://vukhanpur.com/handouts/CS506_handouts_1_45.pdf"},
      { id: 57, title : "CS507 - Information System",  pdfUrl:"https://vukhanpur.com/handouts/CS507_-_Information_Systems_(Lecture_1_-_45).pdf"},
      { id: 58, title : "CS508 - Modern Programming Languages",  pdfUrl:"https://vukhanpur.com/handouts/CS508_handouts_1_45.pdf"},
      { id: 59, title : "CS510 - Software Requirement and Specification",  pdfUrl:"https://vukhanpur.com/handouts/CS510_Software_Requirements_and_Specification_by_SA.pdf"},
      { id: 60, title : "CS601 - Data Communication",  pdfUrl:"https://vukhanpur.com/handouts/cs601_latest.pdf"},
      { id: 61, title : "CS602 - Computer Graphics",  pdfUrl:"https://vukhanpur.com/handouts/CS602_handouts_1_45.pdf"}, 
      { id: 62, title : "CS603 - Software Architecture and Design",  pdfUrl:"https://vukhanpur.com/handouts/CS603_Handouts(MID_TERM).pdf"},
      { id: 63, title : "CS604 - Operating System",  pdfUrl:"https://vukhanpur.com/handouts/CS604_handouts_1_45.pdf"},
      { id: 64, title : "CS605 - Software Engineering II",  pdfUrl:"https://vukhanpur.com/handouts/SoftwareEngineeringII.pdf"}, 
      { id: 65, title : "CS606 - Compiler Construction",  pdfUrl:"https://vukhanpur.com/handouts/CS606_handouts_1_45_(1).pdf"}, 
      { id: 66, title : "CS607 - Artificial Intelligence",  pdfUrl:"https://vukhanpur.com/handouts/CS607_handouts_1_45.pdf"}, 
      { id: 67, title : "CS609 - System Programming",  pdfUrl:"https://vukhanpur.com/handouts/CS609_handouts_1_45.pdf"}, 
      { id: 68, title : "CS610 - Computer Networks",  pdfUrl:"https://vukhanpur.com/handouts/CS610-Handouts.pdf"}, 
      { id: 69, title : "CS611 - Software Quality Engineering",  pdfUrl:"https://vukhanpur.com/handouts/CS611_Handouts.pdf"}, 
      { id: 70, title : "CS614 - Data Warehousing",  pdfUrl:"https://vukhanpur.com/handouts/CS614_handouts_1_45.pdf"}, 
      { id: 71, title : "CS615 - Software Project Management",  pdfUrl:"https://vukhanpur.com/handouts/CS615_updated_handouts.pdf"}, 
      { id: 72, title : "CS701 - Theory Of Computation",  pdfUrl:"https://vukhanpur.com/handouts/CS-701_Handouts_CareerSee.pdf"}, 
      { id: 73, title : "CS702 - Advanced Algorithms Analysis and Design",  pdfUrl:"https://vukhanpur.com/handouts/CS702_handouts_1_45.pdf"}, 
      { id: 74, title : "CS706 - Software Quality Assurance",  pdfUrl:"https://vukhanpur.com/handouts/CS706_Software_Quality_Assurance_Complete_Handouts_[_Downloded_From_Cluesbook.Com].pdf"}, 
      { id: 75, title : "CS707 - Network Security",  pdfUrl:"https://vukhanpur.com/handouts/CS707_Network_Security_Complete_Handouts_[Downloded_From_Cluesbook.Com].pdf"}, 
      { id: 76, title : "CS710 - Mobile and Pervasive Computing",  pdfUrl:"https://vukhanpur.com/handouts/CS710_Mobile_and_Pervasive_Computing_Complete_Handouts_[Downloded_From_Cluesbook.Com].pdf"}, 
      { id: 77, title : "CS711 - Software Design",  pdfUrl:"https://vukhanpur.com/handouts/CS711_handouts_1_45.pdf"}, 
      { id: 78, title : "CS712 - Distributed DBMS",  pdfUrl:"https://vukhanpur.com/handouts/1_to_24_ddbs.pdf"}, 
      { id: 79, title : "CS726 - Information Retrieval Techniques",  pdfUrl:"https://vukhanpur.com/handouts/CS726_Information_Retrieval_Techniques_Complete_Handouts_[Downloded_From_Cluesbook.Com].pdf"}, 
      { id: 80, title : "ECO401 - Economics",  pdfUrl:"https://vukhanpur.com/handouts/ECO401_handouts_1_45.pdf"}, 
      { id: 81, title : "ECO401 - Economics",  pdfUrl:"https://vukhanpur.com/handouts/ECO401_handouts_1_451.pdf"}, 
      { id: 82, title : "ECO402 - Micro Economics",  pdfUrl:"https://vukhanpur.com/handouts/ECO402_handouts_1_45.pdf"}, 
      { id: 83, title : "ECO403 - Macroeconomics",  pdfUrl:"https://vukhanpur.com/handouts/ECO403_handouts_1_45.pdf"}, 
      { id: 84, title : "ECO404 - Managerial Economics",  pdfUrl:"https://vukhanpur.com/handouts/ECO404_handouts_1_45.pdf"}, 
      { id: 85, title : "ECO501 - Development Economics",  pdfUrl:"https://vukhanpur.com/handouts/ECO501_handouts_1_45.pdf"}, 
      { id: 86, title : "ECO601 - Business Econometrics",  pdfUrl:"https://vukhanpur.com/handouts/ECO601_handouts_1_45.pdf"}, 
      { id: 87, title : "ECO606 - Mathematical Economics I",  pdfUrl:"https://vukhanpur.com/handouts/ECO606_Mathematical_Economics_I_Complete_Handouts.pdf"}, 
      { id: 88, title : "EDU401 - Contemporary Issues and Trends in Education",  pdfUrl:"https://vukhanpur.com/handouts/EDU401.pdf"}, 
      { id: 89, title : "EDU406 - Critical Thinking and reflective Practice",  pdfUrl:"https://vukhanpur.com/handouts/EDU406-Complete_Handouts_Topicwise.pdf"}, 
      { id: 90, title : "EDU431 - Test Development & Evaluation",  pdfUrl:"https://vukhanpur.com/handouts/EDU431.pdf"}, 
      { id: 91, title : "EDU601 - Philosophy of Education",  pdfUrl:"https://vukhanpur.com/handouts/EDU_601Complete_handouts.pdf"}, 
      { id: 92, title : "EDU602 - Educational Leadership and Management",  pdfUrl:"https://vukhanpur.com/handouts/EDU_602.pdf"}, 
      { id: 93, title : "EDU101 - Foundation of Education",  pdfUrl:"https://vukhanpur.com/handouts/EDU101_Foundations_of_Education.docx"}, 
      { id: 94, title : "EDU201 - Learning Theories",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_EDU_201.pdf"}, 
      { id: 95, title : "EDU301 - Essentials of Genetics",  pdfUrl:"https://vukhanpur.com/handouts/BIO301_handouts_1_167.pdf"},
      { id: 96, title : "EDU302 - Human Development and Learning",  pdfUrl:"https://vukhanpur.com/handouts/EDU302__Human_Development_and_Learning___handouts_(_topic_1_to_15_).pdf"}, 
      { id: 97, title : "EDU303 - Child Development",  pdfUrl:"https://vukhanpur.com/handouts/Handouts-EDU303.pdf"}, 
      { id: 98, title : "EDU304 - Introduction to Guidance and Counselling",  pdfUrl:"https://vukhanpur.com/handouts/Final_Handouts_EDU304.docx"}, 
      { id: 99, title : "EDU305 - Classroom Management",  pdfUrl:"https://vukhanpur.com/handouts/EDU305_Handouts.pdf"}, 
      { id: 100, title : "EDU402 - Curriculum Development",  pdfUrl:"https://vukhanpur.com/handouts/EDU_402_Handout_Updated.pdf"}, 
      { id: 101, title : "EDU403 - Art, Crafts and Calligraphy",  pdfUrl:"https://vukhanpur.com/handouts/EDU403_Handouts.pdf"}, 
      { id: 102, title : "EDU405 - Classroom Management",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_EDU_405.pdf"}, 
      { id: 103, title : "EDU410 - Teaching of Literacy Skills",  pdfUrl:"https://vukhanpur.com/handouts/EDU410.pdf"}, 
      { id: 104, title : "EDU411 - Teaching of Urdu",  pdfUrl:"https://vukhanpur.com/handouts/edu_411_final_lecture_handouts.pdf"}, 
      { id: 105, title : "EDU430 - ICT in Education",  pdfUrl:"https://vukhanpur.com/handouts/EDU_430.pdf"}, 
      { id: 106, title : "EDU431 - Test Development and Evaluation",  pdfUrl:"https://vukhanpur.com/handouts/EDU431_Final_Handout_EDU431_Fall_2019.pdf"}, 
      { id: 107, title : "EDU433 - Professionalism in Teaching",  pdfUrl:"https://vukhanpur.com/handouts/EDU433_Professionalism_In_Teaching_Complete_Handouts.pdf"}, 
      { id: 108, title : "EDU501 - School, Community and Teacher",  pdfUrl:"https://vukhanpur.com/handouts/New_Complete_Booklet_EDU_501.docx"}, 
      { id: 109, title : "EDU505 - Education Development in Pakistan",  pdfUrl:"https://vukhanpur.com/handouts/EDU505_Education_Development_in_Pakistan_Complete_Handouts.pdf"}, 
      { id: 110, title : "EDU510 - Teaching of Mathematics",  pdfUrl:"https://vukhanpur.com/handouts/EDU510_Handouts.pdf"}, 
      { id: 111, title : "EDU512 - Teaching of Islamic Studies",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_of_Teaching_of_Islamic_Studies_(EDU-512).pdf"}, 
      { id: 112, title : "EDU516 - Teaching of English",  pdfUrl:"https://vukhanpur.com/handouts/edu516.pdf"}, 
      { id: 113, title : "EDU604 - Comparative Education",  pdfUrl:"https://vukhanpur.com/handouts/EDU604_Full_handouts_of.pdf"}, 
      { id: 114, title : "EDU654 - Addressing Problem of learning through technology",  pdfUrl:"https://vukhanpur.com/handouts/HAndouts_EDU_654.pdf"}, 
      { id: 115, title : "ENG001 - Elementary English",  pdfUrl:"https://vukhanpur.com/handouts/ENG001075243.pdf"}, 
      { id: 116, title : "ENG101 - English Comprehension",  pdfUrl:"https://vukhanpur.com/handouts/ENG101_handouts_1_45.pdf"}, 
      { id: 117, title : "ENG201 - Business and Technical English Writing",  pdfUrl:"https://vukhanpur.com/handouts/ENG201_Handouts_Final.pdf"}, 
      { id: 118, title : "ENG301 - Business Communication",  pdfUrl:"https://vukhanpur.com/handouts/Business_Communication_ENG301(1).pdf"}, 
      { id: 119, title : "ENG301 - Business Communication",  pdfUrl:"https://vukhanpur.com/handouts/ENG301_handouts_1_45.pdf"}, 
      { id: 120, title : "ENG401 - Introduction to Literature: Short Story and Poetry",  pdfUrl:"https://vukhanpur.com/handouts/ENG401_handouts_1_15.pdf"}, 
      { id: 121, title : "ENG501 - History of English Language",  pdfUrl:"https://vukhanpur.com/handouts/eng501__Handouts_of_History_of_English_Language.pdf"}, 
      { id: 122, title : "ENG502 - Introduction to Linguistics",  pdfUrl:"https://vukhanpur.com/handouts/Eng502_Handouts_Final_reviewed.pdf"}, 
      { id: 123, title : "ENG503 - Introduction to English Language Teaching",  pdfUrl:"https://vukhanpur.com/handouts/ENG_503_-Handouts_(1).pdf"}, 
      { id: 124, title : "ENG504 - Second Language Acquisition",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_SLA_ENG504.pdf"}, 
      { id: 125, title : "ENG505 - Language Learning",  pdfUrl:"https://vukhanpur.com/handouts/ENG505_Handouts_File_Final-pdf.pdf"}, 
      { id: 126, title : "ENG506 - World Englishes",  pdfUrl:"https://vukhanpur.com/handouts/ENG506_COMPLETE.pdf"}, 
      { id: 127, title : "ENG507 - Phonetics and Phonology",  pdfUrl:"https://vukhanpur.com/handouts/Handouts-ENG507_(1).pdf"}, 
      { id: 128, title : "ENG508 - Semantics and Pragmatics ",  pdfUrl:"https://vukhanpur.com/handouts/ENG-508_Handouts.pdf"}, 
      { id: 129, title : "ENG509 - Morphology and Syntax",  pdfUrl:"https://vukhanpur.com/handouts/ENG509_Handouts_new_(1).pdf"}, 
      { id: 130, title : "ENG510 - Sociolinguistics",  pdfUrl:"https://vukhanpur.com/handouts/Sociolinguistics_ENG510_handouts.pdf"}, 
      { id: 131, title : "ENG511 - Psycholinguistics",  pdfUrl:"https://vukhanpur.com/handouts/Psycholinguistics_ENG511-Handouts.pdf"}, 
      { id: 132, title : "ENG512 - Bilingualism",  pdfUrl:"https://vukhanpur.com/handouts/Handouts__Bilingualism_ENG512.pdf"}, 
      { id: 133, title : "ENG513 - Language Teaching Methods",  pdfUrl:"https://vukhanpur.com/handouts/ENG513_Handouts_(1).pdf"}, 
      { id: 134, title : "ENG514 - Teaching of Listening and Speaking Skills",  pdfUrl:"https://vukhanpur.com/handouts/ENG514_Handouts_updated.pdf"}, 
      { id: 135, title : "ENG515 - Teaching of Reading and Writing Skills",  pdfUrl:"https://vukhanpur.com/handouts/ENG515_Teaching_of_Reading_and_writing_Skills.pdf"}, 
      { id: 136, title : "ENG516 - Teaching Business Communication",  pdfUrl:"https://vukhanpur.com/handouts/ENG516_Teaching_of_English_-_Handouts.pdf"}, 
      { id: 137, title : "ENG517 - Computer Assisted Language Learning",  pdfUrl:"https://vukhanpur.com/handouts/Eng_517-_CALL-_Handouts_new_(1).pdf"}, 
      { id: 138, title : "ENG518 - Research Methodology in ELT",  pdfUrl:"https://vukhanpur.com/handouts/ENG518_Handouts_File_(1).pdf"}, 
      { id: 139, title : "ENG519 - Curriculum Design",  pdfUrl:"https://vukhanpur.com/handouts/ENG519_Handouts.pdf"}, 
      { id: 140, title : "ENG520 - Testing and Assessment",  pdfUrl:"https://vukhanpur.com/handouts/ENG520_Handouts.pdf"}, 
      { id: 141, title : "ENG521 - Language Classroom Management",  pdfUrl:"https://vukhanpur.com/handouts/ENG521_Hnadouts.pdf"}, 
      { id: 142, title : "ENG522 - Applied Linguistics",  pdfUrl:"https://vukhanpur.com/handouts/ENG522_COMPLETE_HANDOUTS.pdf"}, 
      { id: 143, title : "ENG523 - Discourse Analysis",  pdfUrl:"https://vukhanpur.com/handouts/ENG523_Discourse_Analysis_Complete_Handouts_[Downloaded_From_Cluesbook.com].pdf"}, 
      { id: 144, title : "ETH202 - Ethics (for Non-Muslims)",  pdfUrl:"https://vukhanpur.com/handouts/ETH202.pdf"}, 
      { id: 145, title : "FIN621 - Financial Statement Analysis",  pdfUrl:"https://vukhanpur.com/handouts/FIN621_handouts_1_45.pdf"}, 
      { id: 146, title : "FIN622 - Corporate Finance",  pdfUrl:"https://vukhanpur.com/handouts/FIN622_handouts_1_45.pdf"}, 
      { id: 147, title : "FIN623 - Taxation Management",  pdfUrl:"https://vukhanpur.com/handouts/FIN623_handouts_1_45.pdf"}, 
      { id: 148, title : "FIN625 - Credit & Risk Management",  pdfUrl:"https://vukhanpur.com/handouts/FIN625_handouts_1_45.pdf"}, 
      { id: 149, title : "FIN630 - Investment Analysis & Portfolio Management",  pdfUrl:"https://vukhanpur.com/handouts/FIN630_handouts_1_45.pdf"}, 
      { id: 150, title : "GSC101 - General Science",  pdfUrl:"https://vukhanpur.com/handouts/GSC101_Handouts.pdf"}, 
      { id: 151, title : "HRM624 - Conflict Management",  pdfUrl:"https://vukhanpur.com/handouts/HRM624_handouts_1_45.pdf"}, 
      { id: 152, title : "HRM627 - Human Resource Development",  pdfUrl:"https://vukhanpur.com/handouts/HRM627_handouts_1_45.pdf"}, 
      { id: 153, title : "HRM627 - Human Resource Development",  pdfUrl:"https://vukhanpur.com/handouts/HRM627_handouts_1_451.pdf"}, 
      { id: 154, title : "ISL202 - Islamic Studies",  pdfUrl:"https://vukhanpur.com/handouts/ISL202_Complete_Handouts_1-30.pdf"}, 
      { id: 155, title : "IT430 - E-Commerce",  pdfUrl:"https://vukhanpur.com/handouts/IT430_handouts_1_45.pdf"}, 
      { id: 156, title : "MCM101 - Introduction to Mass Communication",  pdfUrl:"https://vukhanpur.com/handouts/FINAL_latest_MCM101;.pdf"}, 
      { id: 157, title : "MCM301 - Communication Skills",  pdfUrl:"https://vukhanpur.com/handouts/mcm301_handouts_1_45.pdf"}, 
      { id: 158, title : "MCM304 - Mass Media in Pakistan",  pdfUrl:"https://vukhanpur.com/handouts/mcm304_handouts_1_45.pdf"}, 
      { id: 159, title : "MCM310 - Journalistic Writing",  pdfUrl:"https://vukhanpur.com/handouts/MCM310_handouts_1_45.pdf"}, 
      { id: 160, title : "MCM311 - Reporting and Sub-Editing",  pdfUrl:"https://vukhanpur.com/handouts/MCM311_handouts_1_45.pdf"}, 
      { id: 161, title : "MCM401 - Fundamentals of Public Relations",  pdfUrl:"https://vukhanpur.com/handouts/MCM401_handouts_1_45.pdf"}, 
      { id: 162, title : "MCM411 - Introduction to Broadcasting",  pdfUrl:"https://vukhanpur.com/handouts/MCM411_handouts_1_45.pdf"}, 
      { id: 163, title : "MCM431 - Development Communication",  pdfUrl:"https://vukhanpur.com/handouts/MCM431_handouts_1_15.pdf"}, 
      { id: 164, title : "MCM501 - Advertising for Print and Electronic Media",  pdfUrl:"https://vukhanpur.com/handouts/MCM501_handouts_1_15.pdf"}, 
      { id: 165, title : "MCM511 - Theories of Communication",  pdfUrl:"https://vukhanpur.com/handouts/MCM511_handouts_1_45.pdf"}, 
      { id: 166, title : "MCM514 - Feature & Column Writing",  pdfUrl:"https://vukhanpur.com/handouts/MCM514_handouts_1_45.pdf"}, 
      { id: 167, title : "MCM515 - Radio News Reporting & Production",  pdfUrl:"https://vukhanpur.com/handouts/MCM515_handouts_1_45.pdf"}, 
      { id: 168, title : "MCM516 - TV News Reporting & Production",  pdfUrl:"https://vukhanpur.com/handouts/MCM516_handouts_1_45.pdf"}, 
      { id: 169, title : "MCM517 - Online Journalism",  pdfUrl:"https://vukhanpur.com/handouts/Online_Journalism_mcm517.pdf"}, 
      { id: 170, title : "MCM520 - Contemporary Mass Media",  pdfUrl:"https://vukhanpur.com/handouts/MCM520_handouts_1_15.pdf"}, 
      { id: 171, title : "MCM531 - Community Journalism",  pdfUrl:"https://vukhanpur.com/handouts/MCM531_handouts_1_15.pdf"}, 
      { id: 172, title : "MCM532 - Magazine Journalism",  pdfUrl:"https://vukhanpur.com/handouts/MCM532_handouts_1_15.pdf"}, 
      { id: 173, title : "MCM601 - Media Management",  pdfUrl:"https://vukhanpur.com/handouts/Media_Management_mcm601.pdf"}, 
      { id: 174, title : "MCM604 - International Communication",  pdfUrl:"https://vukhanpur.com/handouts/MCM604_handouts_1_15.pdf"}, 
      { id: 175, title : "MCM610 - Mass Communication Law & Ethics",  pdfUrl:"https://vukhanpur.com/handouts/MCM610_handouts_1_15.pdf"}, 
      { id: 176, title : "MCM610 - Mass Communication Law & Ethics",  pdfUrl:"https://vukhanpur.com/handouts/MCM610_handouts_1_151.pdf"}, 
      { id: 177, title : "MGMT623 - Knowledge Management",  pdfUrl:"https://vukhanpur.com/handouts/MGMT6231.pdf"}, 
      { id: 178, title : "MGMT623 - Leadership & Team Management",  pdfUrl:"https://vukhanpur.com/handouts/MGMT623.pdf"}, 
      { id: 179, title : "MGMT611 - Human Relations (alt.code:HRM611)",  pdfUrl:"https://vukhanpur.com/handouts/MGMT611_handouts_1_45.pdf"}, 
      { id: 180, title : "MGMT625 - Change Management",  pdfUrl:"https://vukhanpur.com/handouts/MGMT625_handouts_1_45.pdf"}, 
      { id: 181, title : "MGMT627 - Project Management",  pdfUrl:"https://vukhanpur.com/handouts/MGMT627_handouts_1_45.pdf"}, 
      { id: 182, title : "MGMT630 - Knowledge Management",  pdfUrl:"https://vukhanpur.com/handouts/MGMT630_handouts_1_45.pdf"}, 
      { id: 183, title : "MGT101 - Financial Accounting",  pdfUrl:"https://vukhanpur.com/handouts/MGT101_-_Financial_Accounting_-_I_Updated_5,_2017_2.pdf"}, 
      { id: 184, title : "MGT111 - Introduction to Public Administration",  pdfUrl:"https://vukhanpur.com/handouts/mgt111_complete.pdf"}, 
      { id: 185, title : "MGT201 - Financial Management",  pdfUrl:"https://vukhanpur.com/handouts/MGT201_handouts_1_45.pdf"}, 
      { id: 186, title : "MGT211 - Introduction to Business",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_MGT211_-_Updated.pdf"}, 
      { id: 187, title : "MGT211 - Introduction to Business",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_MGT211_-_Updated1.pdf"}, 
      { id: 188, title : "MGT211 - Introduction to Business",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_MGT211_-_Updated2.pdf"}, 
      { id: 189, title : "MGT301 - Principles of Marketing",  pdfUrl:"https://vukhanpur.com/handouts/MGT301_handouts_1_45.pdf"}, 
      { id: 190, title : "MGT401 - Financial Accounting II",  pdfUrl:"https://vukhanpur.com/handouts/Hand_outs_MGT401.pdf"}, 
      { id: 191, title : "MGT402 - Cost & Management Accounting",  pdfUrl:"https://vukhanpur.com/handouts/MGT402_handouts_1_45.pdf"}, 
      { id: 192, title : "MGT411 - Money & Banking",  pdfUrl:"https://vukhanpur.com/handouts/MGT411_handouts_1_45.pdf"}, 
      { id: 193, title : "MGT501 - Human Resource Management",  pdfUrl:"https://vukhanpur.com/handouts/MGT501_handouts_1_45.pdf"}, 
      { id: 194, title : "MGT501 - Human Resource Management",  pdfUrl:"https://vukhanpur.com/handouts/MGT501_handouts_1_451.pdf"}, 
      { id: 195, title : "MGT502 - Organizational Behaviour",  pdfUrl:"https://vukhanpur.com/handouts/MGT502_handouts_1_45.pdf"}, 
      { id: 196, title : "MGT502 - Organizational Behaviour",  pdfUrl:"https://vukhanpur.com/handouts/MGT502_handouts_1_451.pdf"}, 
      { id: 197, title : "MGT503 - Principles of Management",  pdfUrl:"https://vukhanpur.com/handouts/MGT503.pdf"}, 
      { id: 198, title : "MGT503 - Principles of Management",  pdfUrl:"https://vukhanpur.com/handouts/MGT5031.pdf"}, 
      { id: 199, title : "MGT504 - Organization Theory & Design",  pdfUrl:"https://vukhanpur.com/handouts/MGT504_handouts_1_45.pdf"}, 
      { id: 200, title : "MGT510 - Total Quality Management",  pdfUrl:"https://vukhanpur.com/handouts/MGT510_handouts_1_45.pdf"}, 
      { id: 201, title : "MGT510 - Total Quality Management",  pdfUrl:"https://vukhanpur.com/handouts/MGT510_handouts_1_451.pdf"}, 
      { id: 202, title : "MGT520 - International Business",  pdfUrl:"https://vukhanpur.com/handouts/MGT520_handouts_1_45.pdf"}, 
      { id: 203, title : "MGT601 - SME Management",  pdfUrl:"https://vukhanpur.com/handouts/MGT601_handouts_1_45.pdf"}, 
      { id: 204, title : "MGT602 - Enterpreneurship",  pdfUrl:"https://vukhanpur.com/handouts/MGT-602_(Handouts)_Entreprenurship.pdf"}, 
      { id: 205, title : "MGT602 - Entrepreneurship",  pdfUrl:"https://vukhanpur.com/handouts/Entreprenurship_MGT-602_(Handouts).pdf"}, 
      { id: 206, title : "MGT603 - Strategic Management",  pdfUrl:"https://vukhanpur.com/handouts/MGT603_handouts_1_45.pdf"}, 
      { id: 207, title : "MGT604 - Management of Financial Institutions (alt.code:BNK604)",  pdfUrl:"https://vukhanpur.com/handouts/BNK604_handouts_1_45.pdf"}, 
      { id: 208, title : "MGT610 - Business Ethics",  pdfUrl:"https://vukhanpur.com/handouts/MGT610_handouts_1_45.pdf"}, 
      { id: 209, title : "MGT611 - Business & Labor Law",  pdfUrl:"https://vukhanpur.com/handouts/MGT611_handouts_1_45.pdf"}, 
      { id: 210, title : "MGT613 - Production/Operations Management",  pdfUrl:"https://vukhanpur.com/handouts/MGT613_handouts_1_45.pdf"}, 
      { id: 211, title : "MGTE630 - Knowledge Management",  pdfUrl:"https://vukhanpur.com/handouts/MGTE630.pdf"}, 
      { id: 212, title : "MKT501 - Marketing Management",  pdfUrl:"https://vukhanpur.com/handouts/MKT501_handouts_1_45.pdf"}, 
      { id: 213, title : "MKT610 - Customer Realtionship Management",  pdfUrl:"https://vukhanpur.com/handouts/MKT610_handouts_1_45.pdf"}, 
      { id: 214, title : "MKT620 - Final Project Marketing",  pdfUrl:"https://vukhanpur.com/handouts/MKT620_handouts.pdf"}, 
      { id: 215, title : "MKT621 - Advertising & Promotion",  pdfUrl:"https://vukhanpur.com/handouts/MKT621_handouts_1_45.pdf"}, 
      { id: 216, title : "MKT624 - Brand Management",  pdfUrl:"https://vukhanpur.com/handouts/MKT624_handouts_1_45.pdf"}, 
      { id: 217, title : "MKT630 - International Marketing",  pdfUrl:"https://vukhanpur.com/handouts/MKT630_handouts_1_45.pdf"}, 
      { id: 218, title : "MTH001 - Elementary Mathematics",  pdfUrl:"https://vukhanpur.com/handouts/MTH001074719.pdf"}, 
      { id: 219, title : "MTH001 - Elementary Mathematics",  pdfUrl:"https://vukhanpur.com/handouts/MTH001074725.pdf"}, 
      { id: 220, title : "MTH100 - General Mathematics",  pdfUrl:"https://vukhanpur.com/handouts/mth_100.pdf"}, 
      { id: 221, title : "MTH101 - Calculus And Analytical Geometry",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_MTH101_Reviewed.pdf"}, 
      { id: 222, title : "MTH102 - Basic Algebra and Trignometry ",  pdfUrl:"https://vukhanpur.com/handouts/MTH102_HANDOUTS.pdf"}, 
      { id: 223, title : "MTH201 - Multivariable Calculus",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_mth201.pdf"}, 
      { id: 224, title : "MTH202 - Discrete Mathematics",  pdfUrl:"https://vukhanpur.com/handouts/MTH202-Discrete-Mathematics-Complete-Handouts-Pdf.pdf"}, 
      { id: 225, title : "MTH301 - Calculus II",  pdfUrl:"https://vukhanpur.com/handouts/mth301(handouts).pdf"}, 
      { id: 226, title : "MTH302 - Business Mathematics and Statistics",  pdfUrl:"https://vukhanpur.com/handouts/MTH302_handouts_1_45.pdf"}, 
      { id: 227, title : "MTH304 - Statics",  pdfUrl:"https://vukhanpur.com/handouts/MTH304_handouts_(1)102343.pdf"}, 
      { id: 228, title : "MTH401 - Equations",  pdfUrl:"https://vukhanpur.com/handouts/hanouts_401_(1).pdf"}, 
      { id: 229, title : "MTH405 - Elementary Topics in Pure Mathematics",  pdfUrl:"https://vukhanpur.com/handouts/Handouts-Metric_Spaces_(mth_405)103331.pdf"}, 
      { id: 230, title : "MTH501 - Linear Algebra",  pdfUrl:"https://vukhanpur.com/handouts/Handuts_of_MTH501_Latest.pdf"}, 
      { id: 231, title : "MTH501 - Linear Algebra",  pdfUrl:"https://vukhanpur.com/handouts/Handuts_of_MTH501_Latest1.pdf"}, 
      { id: 232, title : "MTH601 - Operations Research",  pdfUrl:"https://vukhanpur.com/handouts/MTH601_handouts_1_45.pdf"}, 
      { id: 233, title : "MTH603 - Numeric Analysis",  pdfUrl:"https://vukhanpur.com/handouts/MTH603_Handouts.pdf"}, 
      { id: 234, title : "MTH621 - Real Analysis I",  pdfUrl:"https://vukhanpur.com/handouts/MTH621_Handouts-RealAnalysis.pdf"}, 
      { id: 235, title : "MTH633 - Group Theory",  pdfUrl:"https://vukhanpur.com/handouts/MTH633.pdf"}, 
      { id: 236, title : "MTH634 - Topology",  pdfUrl:"https://vukhanpur.com/handouts/MTH634_Handouts.pdf"}, 
      { id: 237, title : "PAK301 - Pakistan Studies",  pdfUrl:"https://vukhanpur.com/handouts/PAK301_handouts_1_30.pdf"}, 
      { id: 238, title : "PAK302 - Pakistan Studies",  pdfUrl:"https://vukhanpur.com/handouts/PAK302_PPT_vuanswer.com.rar"}, 
      { id: 239, title : "PHY101 - Physics",  pdfUrl:"https://vukhanpur.com/handouts/PHY101-Physics-Complete-Handouts-Pdf.pdf"}, 
      { id: 240, title : "PHY301 - Circuit Theory",  pdfUrl:"https://vukhanpur.com/handouts/PHY301_handouts_1_45.pdf"}, 
      { id: 241, title : "PSC201 - International Relations",  pdfUrl:"https://vukhanpur.com/handouts/PSC201_handouts_1_45.pdf"}, 
      { id: 242, title : "PSC401 - Public International Law",  pdfUrl:"https://vukhanpur.com/handouts/PSC401_handouts_1_45.pdf"}, 
      { id: 243, title : "PSY101 - Introduction to Psycology",  pdfUrl:"https://vukhanpur.com/handouts/PSY101___Introduction_to_Psychology__(Complete).pdf"}, 
      { id: 244, title : "PSY401 - Clinical Psychology",  pdfUrl:"https://vukhanpur.com/handouts/Formatted_Handouts_of_(PSY401).pdf"}, 
      { id: 245, title : "PSY402 - Experimental Psychology",  pdfUrl:"https://vukhanpur.com/handouts/PSY402_lesson_1-15_Final.pdf"}, 
      { id: 246, title : "PSY403 - Social Psychology",  pdfUrl:"https://vukhanpur.com/handouts/PSY403_handouts_1_45.pdf"}, 
      { id: 247, title : "PSY404 - Abnormal Psychology",  pdfUrl:"https://vukhanpur.com/handouts/psy404_Handouts_1-22_Lectures.pdf"}, 
      { id: 248, title : "PSY405 - Personality Psychology",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_psy405.pdf"}, 
      { id: 249, title : "PSY406 - Educational Psychology",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_1-45_(Final)_PSY406.pdf"}, 
      { id: 250, title : "PSY406 - Educational Psychology",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_1-45_(Final)_PSY4061.pdf"}, 
      { id: 251, title : "PSY407 - Sport Psychology",  pdfUrl:"https://vukhanpur.com/handouts/PSY407_handouts_1_45.pdf"}, 
      { id: 252, title : "PSY408 - Health Psychology",  pdfUrl:"https://vukhanpur.com/handouts/Handouts-PSY408.pdf"}, 
      { id: 253, title : "PSY409 - Positive Psychology",  pdfUrl:"https://vukhanpur.com/handouts/Handouts-PSY409.pdf"}, 
      { id: 254, title : "PSY502 - History & Systems of PsychologySY502",  pdfUrl:"https://vukhanpur.com/handouts/PSY502_Handouts.pdf"}, 
      { id: 255, title : "PSY504 - Congitive Psychology",  pdfUrl:"https://vukhanpur.com/handouts/Formatted_Handouts_of_Cognitive_Psychology_(PSY504).pdf"}, 
      { id: 256, title : "PSY505 - Developmental Psychology",  pdfUrl:"https://vukhanpur.com/handouts/Handouts-PSY505.pdf"}, 
      { id: 257, title : "PSY510 - Organizational Psychology",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_510.pdf"}, 
      { id: 258, title : "PSY511 - Environmental Psychology",  pdfUrl:"https://vukhanpur.com/handouts/Handouts-PSY511.pdf"}, 
      { id: 259, title : "PSY511 - Environmental Psychology",  pdfUrl:"https://vukhanpur.com/handouts/PSY511_handouts_1_45.pdf"}, 
      { id: 260, title : "PSY512 - Gender issues in Psychology",  pdfUrl:"https://vukhanpur.com/handouts/Handouts-PSY512.pdf"}, 
      { id: 261, title : "PSY513 - Forensic Psychology",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_of_PSY513.doc"}, 
      { id: 262, title : "PSY514 - Consumer Psychology",  pdfUrl:"https://vukhanpur.com/handouts/Formatted_Handouts_of_Consumer_Psychology_(PSY514).pdf"}, 
      { id: 263, title : "PSY515 - Cross Cultural Psychology",  pdfUrl:"https://vukhanpur.com/handouts/Formatted_Handouts_of_Cross-Cultural__Psychology_(PSY515).pdf"}, 
      { id: 264, title : "PSY610 - Neurological Bases or Behavior",  pdfUrl:"https://vukhanpur.com/handouts/Handouts-PSY610.pdf"}, 
      { id: 265, title : "PSY631 - Psychological Testing & Measurements",  pdfUrl:"https://vukhanpur.com/handouts/PSY631_handouts_1_45.pdf"}, 
      { id: 266, title : "PSY632 - Theory & Practice of Counseling",  pdfUrl:"https://vukhanpur.com/handouts/PSY632_handouts_1_45.pdf"}, 
      { id: 267, title : "PSY632 - Theory & Practice of Counselling",  pdfUrl:"https://vukhanpur.com/handouts/Handouts-PSY632.pdf"}, 
      { id: 268, title : "SOC101 - Introduction to Sociology",  pdfUrl:"https://vukhanpur.com/handouts/SOC101_handouts_1_45.pdf"}, 
      { id: 269, title : "SOC301 - Introduction to Social Work",  pdfUrl:"https://vukhanpur.com/handouts/SOC301_Introduction_to_Social_Work_-_2.pdf"}, 
      { id: 270, title : "SOC302 - Sociological Theories",  pdfUrl:"https://vukhanpur.com/handouts/SOC302.pdf"}, 
      { id: 271, title : "SOC401 - Cultural Anthropology",  pdfUrl:"https://vukhanpur.com/handouts/SOC401_handouts_1_45.pdf"}, 
      { id: 272, title : "SOC402 - Sociological Perspectives",  pdfUrl:"https://vukhanpur.com/handouts/SOC402_Handouts_lesson_01-45_final.pdf"}, 
      { id: 273, title : "SOC403 - Gender Studies",  pdfUrl:"https://vukhanpur.com/handouts/SOC403_Handouts_Lesson_01-45.pdf"}, 
      { id: 274, title : "SOC404 - Pakistan Society and Culture",  pdfUrl:"https://vukhanpur.com/handouts/Handouts_SOC404_Final.pdf"}, 
      { id: 275, title : "SOC602 - Sociology of Education",  pdfUrl:"https://vukhanpur.com/handouts/Handouts.pdf"}, 
      { id: 276, title : "SOC603 - Sociology of Development",  pdfUrl:"https://vukhanpur.com/handouts/Sociology_of_Development_handnotes.pdf"}, 
      { id: 277, title : "SOC611 - Criminology",  pdfUrl:"https://vukhanpur.com/handouts/SOC611_Criminology_Complete_Handouts_[_Downloded_From_Cluesbook.Com].pdf"}, 
      { id: 278, title : "STA630 - Research Methods",  pdfUrl:"https://vukhanpur.com/handouts/STA630.pdf"}, 
      { id: 279, title : "STA301 - Statistics and Probability",  pdfUrl:"https://vukhanpur.com/handouts/STA301_Handouts.pdf"}, 
      { id: 280, title : "STA301 - Statistics and Probablity",  pdfUrl:"https://vukhanpur.com/handouts/STA301-handout.pdf"}, 
      { id: 281, title : "STA630 - Research Method",  pdfUrl:"https://vukhanpur.com/handouts/STA630_handouts_1_45.pdf"}, 
      { id: 282, title : "STA641 - Statistical Packages and its Application",  pdfUrl:"https://vukhanpur.com/handouts/STA641.pdf"}, 
      { id: 283, title : "URD101 - Urdu",  pdfUrl:"https://vukhanpur.com/handouts/URD101_handouts_1_45.pdf"}, 
      { id: 284, title : "ZOO101 - Biological Techniques",  pdfUrl:"https://vukhanpur.com/handouts/ZOO_101_Biological_techniques_handouts_(1).pdf"}, 
      { id: 285, title : "ZOO102 - Principles of Animal Life-I",  pdfUrl:"https://vukhanpur.com/handouts/ZOO102_1p2_PPT_Slide__Laiba_Mahi__.pdf"}, 
      { id: 286, title : "ZOO103 - Principles of Systematics",  pdfUrl:"https://vukhanpur.com/handouts/mlzm_lmly_103_khyn.pdf"}, 
      { id: 287, title : "ZOO201 - Animal Diversity: Invertebrates",  pdfUrl:"https://vukhanpur.com/handouts/Animal_Diversity_Invertebrates_(Zoo201)_Handouts_(1).pdf"}, 
      { id: 288, title : "ZOO301 - Animal Form & Function-I",  pdfUrl:"https://vukhanpur.com/handouts/ZOO301_handouts.pdf"}, 
      { id: 289, title : "Zoo501 - Development Biology",  pdfUrl:"https://vukhanpur.com/handouts/ZOO501-Developmental-Biology-MERGED-PPT-handouts(_TOPIC_1_TO_144_).pdf"}, 
      { id: 290, title : "ZOO503 - Zoogeography and Paleontology",  pdfUrl:"https://vukhanpur.com/handouts/ZOO503-hantdouts-Zoogeography-and-Paleontology-merged-ppt.pdf"}, 
      { id: 291, title : "ZOO504 - Wildlife",  pdfUrl:"https://vukhanpur.com/handouts/ZOO504.pdf"}, 
      { id: 292, title : "Zoo506 - Applied Entomology and Pest Management",  pdfUrl:"https://vukhanpur.com/handouts/ZOO506-Applied-Entomology-And-Pest-Management-full-merged-ppt-handouts(_topic-1_to_134).pdf"}, 
      { id: 293, title : "ZOO507 - Principles of Animal Ecology",  pdfUrl:"https://vukhanpur.com/handouts/ZOO507-Principles-of-Animal-Ecology_UPDATED_COURSE_2021_(_MERGED_PPT_TOPIC_1_TO_95_)_MID_TERM.pdf"}, 
      { id: 294, title : "ZOO510 - Economic Zoology",  pdfUrl:"https://vukhanpur.com/handouts/ZOO510-Economic-Zoology-merged-ppt-handouts-(Topic-no-1-to-239).pdf"}, 
    ];

const Handouts = () => {
  return (
    <View style={styles.body}>
      <FlatList
        data={handoutData}
        keyExtractor={(item) => item.id.toString()}
        renderItem={({ item }) => (
          <BookSection title={item.title} pdfUrl={item.pdfUrl} />
          
        )}
        scrollEnabled={false}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  body: {
    flexDirection: 'column',
  },
});

export default Handouts;
